name: "Book Checker"
version: "1.0.0"
slug: "book_checker"
description: "A Next.js application to check and manage your books."
url: "https://github.com/lordee/book-checker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - share:rw
ports:
  3000/tcp: 3000
options: {}
schema: {}
